<?php
require_once __DIR__.'/inc/config.php';require_login();$id=(int)($_GET['id']??0);$f=['name'=>'','base_url'=>'','verify_tls'=>1,'notes'=>''];
if($id){$s=db()->prepare('SELECT * FROM firewalls WHERE id=?');$s->execute([$id]);$f=$s->fetch()?:$f;}$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{$n=trim((string)$_POST['name']);$u=normalize_url((string)$_POST['base_url']);$v=isset($_POST['verify_tls'])?1:0;$notes=trim((string)($_POST['notes']??''));$k=trim((string)($_POST['api_key']??''));$sec=trim((string)($_POST['api_secret']??''));if($n==='')throw new InvalidArgumentException('Name required.');$now=gmdate('c');
if($id){if($k!==''||$sec!==''){if($k===''||$sec==='')throw new InvalidArgumentException('Enter key and secret.');$s=db()->prepare('UPDATE firewalls SET name=?,base_url=?,api_key_enc=?,api_secret_enc=?,verify_tls=?,notes=?,updated_at=? WHERE id=?');$s->execute([$n,$u,encrypt_value($k),encrypt_value($sec),$v,$notes,$now,$id]);}else{$s=db()->prepare('UPDATE firewalls SET name=?,base_url=?,verify_tls=?,notes=?,updated_at=? WHERE id=?');$s->execute([$n,$u,$v,$notes,$now,$id]);}}
else{if($k===''||$sec==='')throw new InvalidArgumentException('API key and secret required.');$s=db()->prepare('INSERT INTO firewalls(name,base_url,api_key_enc,api_secret_enc,verify_tls,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$n,$u,encrypt_value($k),encrypt_value($sec),$v,$notes,$now,$now]);}header('Location: /');exit;}catch(Throwable $x){$error=$x->getMessage();}}
require __DIR__.'/inc/header.php';?>
<div class="page-title"><h1><?=$id?'Edit':'Add'?> firewall</h1></div><?php if($error):?><div class="alert error"><?=h($error)?></div><?php endif;?>
<form class="form-card" method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><label>Name<input name="name" value="<?=h($f['name'])?>" required></label><label>Web/API URL<input name="base_url" value="<?=h($f['base_url'])?>" placeholder="https://firewall.example.net" required></label><label>API key<input name="api_key" <?=$id?'placeholder="Leave blank to keep current"':'required'?>></label><label>API secret<input type="password" name="api_secret" <?=$id?'placeholder="Leave blank to keep current"':'required'?>></label><label class="checkbox"><input type="checkbox" name="verify_tls" <?=!empty($f['verify_tls'])?'checked':''?>> Verify TLS certificate</label><label>Notes<textarea name="notes"><?=h($f['notes'])?></textarea></label><div class="actions"><button>Save</button><a class="button secondary" href="/">Cancel</a></div></form>
<?php require __DIR__.'/inc/footer.php';?>
